### ISSUE TITLE
Possibly it would be easier to use Alure?

### ISSUE THREAD

**Issue by mrsndmn** [Test-More/Test2-Harness-UI#21]
https://github.com/allure-framework/allure2/

I think it is possible to teach alure to parse Test2-Harness logs.

**Comment by exodist** [comment]
It would probably be easier. It also would have been easier for Larry Wall to keep using C instead of inventing perl. It would also have been easier to keep using Test-Harness, or running tests by hand without a harness. But taking the easy way never produces anything worthwhile.

It is very hard for me not to read your message as an attack, and I am really hoping that is just a misunderstanding, possibly cultural? Projects like Test2-Harness are a passion project, and suggesting an "easier" alternative that is not actually capable of achieving any of my personal goals for my project strongly implies only an idiot would bother writing a project like Test2-Harness, and that I must therefor be an idiot.

Test2-Harness meets the following essential goals, many of which cannot be met by allure, or other tools:

- It is written in perl and thus able to preload perl modules and then fork to run tests with a lot of work already done providing a performance boost.
- It understands test2 natively and does not need to be "taught" how to do it.
- It provides shortcuts for perl essentials like Devel::Cover that provide code coverage metrics
- Many Many more, see the list of features currently in yath.

**Comment by mrsndmn** [comment]
> It is very hard for me not to read your message as an attack, and I am really hoping that is just a misunderstanding, possibly cultural?

Sorry, I didn't want it to sound like that.

I got your point of view.
Thank you!
